### ISSUE TITLE
Improve and adjust build configuration and makefiles

### ISSUE THREAD

**Issue by annacruz** [otrv4/libotr-ng-toolkit#11]
Before the work begin is good to:
- Have the build passing and also being well configured to not take longer than it's necessary.
- Check if the makefiles provides all the necessary steps/functions to the toolkit be running smoothly (This include the makefile of the test as well)

**Comment by claucece** [comment]
It will be nice to add 'code-style' too as well as checking if the 'm4' folder is updated to the latest versions.

**Comment by annacruz** [comment]
created issue #16 to configure the code-style
